In [33]:
import pandas as pd

ventas = pd.DataFrame({
        'producto': [
            'Monitor', 'Auriculares', 'Webcam', 'Impresora', 'Tablet',
            'Disco SSD', 'Memoria RAM', 'Altavoces', 'Cargador', 'Cable HDMI',
            'Router', 'Smartphone', 'Silla', 'Mesa', 'Micrófono',
            'Teclado', 'Mouse', 'Laptop', 'Monitor', 'Auriculares'
        ],
        'precio': [
            300, 60, 90, 180, 450,
            100, 70, 45, 30, 15,
            75, 800, 250, 180, 120,
            65, 20, 1400, 350, 85
        ],
        'stock': [
            10, 30, 15, 8, 12,
            25, 40, 18, 35, 50,
            14, 6, 7, 10, 9,
            22, 60, 3, 8, 25
        ]
    })

### Mostrar las 5 primeras filas

In [34]:
ventas.head() # Si le pasamos un entero, muestra ese número de registros

      producto  precio  stock
0      Monitor     300     10
1  Auriculares      60     30
2       Webcam      90     15
3    Impresora     180      8
4       Tablet     450     12

### Mostrar las 5 últimas filas

In [35]:
ventas.tail() # Si le pasamos un entero, muestra ese número de registros

       producto  precio  stock
15      Teclado      65     22
16        Mouse      20     60
17       Laptop    1400      3
18      Monitor     350      8
19  Auriculares      85     25

### Mostrar registros al azar

In [36]:
ventas.sample(3)

     producto  precio  stock
0     Monitor     300     10
5   Disco SSD     100     25
10     Router      75     14

### Mostrar la información de la estructura del df

In [37]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   producto  20 non-null     object
 1   precio    20 non-null     int64
 2   stock     20 non-null     int64
dtypes: int64(2), object(1)
memory usage: 612.0+ bytes

### Mostrar información del diseño del df

In [40]:
ventas.shape # Filas, Columnas

(20, 3)

### Mostrar los tipos de datos

In [41]:
ventas.dtypes

producto    object
precio       int64
stock        int64
dtype: object

### Mostrar estadísticas descriptivas básicas

In [42]:
ventas.describe()

            precio     stock
count    20.000000  20.00000
mean    234.250000  20.35000
std     332.966234  15.67524
min      15.000000   3.00000
25%      63.750000   8.75000
50%      95.000000  14.50000
75%     262.500000  26.25000
max    1400.000000  60.00000